version: 2
updates:
  
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: "weekly"
  ignore:
    # Target a low version of FSharp.Core, for max compat
    - dependency-name: "FSharp.Core"
