name: CI

on:
  push:
  pull_request:
  schedule:
    # Run daily at 00:00 so we get notified if CI is broken before a pull request
    # is submitted.
    - cron:  '0 0 * * *'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

permissions:
  contents: read

jobs:

    # .NET Setup
    - name: Setup .NET SDK v9.0.x
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x


    # Build
    - name: .NET Build
      run: |
        dotnet build


    # Test
    - name: .NET Test
      run: |
        dotnet test
